In [69]:
import pandas as pd
import numpy as np
df = pd.read_csv("titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [70]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [71]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived
target.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [72]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

female   male
0   False   True
1    True  False
2    True  False

In [73]:
inputs = pd.concat([inputs,dummies] , axis = 'columns')
inputs.head()


Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False
3       1  female  35.0  53.1000    True  False
4       3    male  35.0   8.0500   False   True

In [74]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [75]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [76]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(10)

Pclass        Age     Fare  female
0       3  22.000000   7.2500   False
1       1  38.000000  71.2833    True
2       3  26.000000   7.9250    True
3       1  35.000000  53.1000    True
4       3  35.000000   8.0500   False
5       3  29.699118   8.4583   False
6       1  54.000000  51.8625   False
7       3   2.000000  21.0750   False
8       3  27.000000  11.1333    True
9       2  14.000000  30.0708    True

In [77]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2)

In [78]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [79]:
model.fit(X_train ,y_train)
model.score(X_test,y_test)

0.7374301675977654

In [80]:
X_test[0:10]

Pclass        Age      Fare  female
778       3  29.699118    7.7375   False
381       3   1.000000   15.7417    True
170       1  61.000000   33.5000   False
673       2  31.000000   13.0000   False
88        1  23.000000  263.0000    True
70        2  32.000000   10.5000   False
836       3  21.000000    8.6625   False
288       2  42.000000   13.0000   False
693       3  25.000000    7.2250   False
265       2  36.000000   10.5000   False

In [81]:
y_test[0:10]

778    0
381    1
170    0
673    1
88     1
70     0
836    0
288    1
693    0
265    0
Name: Survived, dtype: int64

In [82]:
model.predict(X_test[0:10])

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [83]:
model.predict_proba(X_test[:10])

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

<h2 style='color:skyblue'>Calculate the score using cross validation<h2>

In [84]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.76223776, 0.82517483, 0.71830986, 0.81690141, 0.79577465])